# Generated by Django 6.0.4 on 2026-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='course',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='full_name',
            field=models.TextField(),
        ),
    ]
